### ISSUE TITLE
Unknown setting

### ISSUE THREAD

**Issue by archusXIV** [anoopar112/bspwm-dual-monitors#2]
hi anoop, I use bspwm for years now and I looked at your bspwnrc and noticed something strange...
You are using:
`bspc config focused_locked_border_color     '#ffffff'`
but in the terminal bspc says "config: Unknown setting: 'focused_locked_border_color'."
How to you make it work?
[My config](https://github.com/archusXIV/dotfiles/blob/main/bspwm/bspwmrc)

**Comment by anoopar112** [comment]
Yes, this was an old setting, it was removed when it hit 0.9.1 
https://github.com/baskerville/bspwm/blob/8fc2269fe0f29a785885bcd9122812eae7226d7b/doc/CHANGELOG.md#from-09-to-091
